version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app/server
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/app/client/src
      - ./client/index.html:/app/client/index.html
      - node_modules:/app/client/node_modules
    ports:
      - 5173:5173
    depends_on:
      - server
    networks:
      - app-network
volumes:
  node_modules:

networks:
  app-network:
    driver: bridge